### PR TITLE
Issue#1233 extended snapshots task

### PR DESCRIPTION
**Pull request by MFlyer**
#1233 - Pull request depending on js libs repository update (cron-window)

@schakrava : I've made lot of testing and all seem to be fine

### CODE REVIEW

**Comment by schakrava** [comment]
Thanks for all your work @MFlyer . I look forward to testing it in the next couple of days.

**Comment by MFlyer** [comment]
It's a pleasure @schakrava :)

**Comment by schakrava** [comment]
Really nice work @MFlyer. I am sure to use this feature, very useful!

**Comment by MFlyer** [comment]
Great @schakrava, happy cos' you'll use it :smile: - and now i can delete that branch too!! eheh

**Pull request merged**
