### PR TITLE
Issue#1083 issue#978 testmail and gmail auth

### PR DESCRIPTION
**Pull request by MFlyer**
Reference to #1083 and #978 

To @schakrava 
Google accounts problem : added reference to google pages (how to allow access to unsecure apps)
"Mail sent" : modified with a kind message like "mail queued" (no grant about message arriving.

Except these 2 small things, our new smtp auth check function tell if entered smtp configs are ok ( try a real login to smtp server :wink: )

Note: this had to be done on config page because smtp.login requires smtp password, not stored on Rockstor db (so doing we don't store it and this is good)

Flyer

P.S.: Don't care about first commit reference to #738 - just a mistake

### CODE REVIEW

**Comment by phillxnet** [comment]
@MFlyer Only had a quick look but in one of the commits so far you recommend that gmail's security setting requires lowering; last I knew this was not necessary but a work around to accommodate poor / old clients and we shouldn't need this (it is often done in error just to get things working). See my forum post for details, in there I reference a GitHub shell script that I used which at least way back when I tried it did not require lowering my gmail settings, I reference the script just as it contains the required configuration. Took me ages to find out too. I used it to automate the setup of the same mail server program as Rockstor uses for an Ubuntu server's notifications.
https://forum.rockstor.com/t/error-notifications-and-status-notifications-email/143/2
https://forum.rockstor.com/t/error-notifications-and-status-notifications-email/143/4

Well done on replacing those pesky TAB characters, we are getting there on those.

**Comment by phillxnet** [comment]
@MFlyer It may be that the modifications necessary to support the more secure gmail requirements are outside the scope of this pr, in which case we can always open another issue to address what is necessary. And apologies if this is all nonsense now, but I did run into this and did solve it way back and so it would be good to implement the same in Rockstor if it is still a valid method.

Great stuff here as usual by the way.

**Comment by MFlyer** [comment]
Hi @phillxnet , thanks for your checks!! I had same doubt about lowering gmail security and found your solution proposed on web too, but pls check current Rockstor `/etc/postfix/main.cf` that is running like your.

Possible solution: Do a real check for gmail accounts (not just a warning) and provide a custom function for that.

Flyer

**Comment by MFlyer** [comment]
Good morning @phillxnet ,
had some testing over gmail/google starting from your github page :sunglasses: (i see it's from 2014) and actually gmail account access has become hard, with only 2 options:
- Enable less secure apps access
- Enable Google 2-step verification (every time you login will require pass+one time password via sms or similar) that let you add auth for other apps (create a special new password for your gmail account instead of one normally used)

Finally,
I think our current PR can be considered OK

**Comment by phillxnet** [comment]
@MFlyer Yes very much advised to use special password and that is what I did. Very bad practice to use master password for gmail account in an appliance of any sort. I also had 2 factor enabled and as an appliance can't ask for the 2nd factor it is required to setup a special purpose password. It then doesn't have as many rights as the master password and can be used in circumstance where a second factor is not required. From memory that was my setup, ie 2 factor and special app password; which has been general practice on gmail for some time now. Nice as you can easily label the various 'apps' that have access and disable that particular access without messing up all other access points.

You new text is great. Sorry to be meddling here, your stuff is always good but it was just my little chip in as I think we don't want to be encouraging lowering security settings; as you mentioned yourself.

Cheers.

The real check login is a great improvement here, well done.

**Comment by MFlyer** [comment]
Thanks @phillxnet :)

**Comment by schakrava** [comment]
Nice work @MFlyer and thanks for your collaboration @phillxnet . LGTM.

**Pull request merged**
