### PR TITLE
Fixes #1617 but still some errors on rockstor.log

### LINKED ISSUE #1617: [Bug - urgent] Missing dependency over Rockstor api_wrapper.py
After recent 3.8.16-7 we've lost a piece of code on api_wrapper

from oauth2_provider.models import AccessToken

### PR DESCRIPTION
**Pull request by MFlyer**
Related to #1617,
partially fixes recent changes on flake8 tests granting system boot + WebUI access

to @schakrava ready to be merged, but some errors still running

Mirko

### CODE REVIEW

**Comment by schakrava** [comment]
I am not convinced this is a fix. We are not using that object, why import it?

**Comment by MFlyer** [comment]
To @phillxnet  too
Well, you're totally right about that and after panicing, having a second reboot, Rockstor WebUI running without any mod

Closing PR and issue too

**Comment by phillxnet** [comment]
@MFlyer Had you executed any build commands in that test tree? I still have a non working Web-UI example here after reboots, but no build executed there in. Just straight install of 3.8.16-1 and up to -7.

**Comment by MFlyer** [comment]
Hi @phillxnet no builds, just reboots, are you accessing it via hostname or ip?
My steps:
access with ip, reboot, back to console -> all fine
access with hostname, reboot, back to console -> errors

Check this, second tail is after a reboot from a http://hostname/ Rockstor WebUI

```
[root@rocktest ~]# tail -f /opt/rockstor/var/log/rockstor.log

[17/Jan/2017 15:49:55] DEBUG [storageadmin.views.command:152] Bootstrap operations completed
[17/Jan/2017 15:50:02] DEBUG [fs.btrfs:713] Quota inconsistency while assigning 0/36558. Rescan scheduled.
[17/Jan/2017 15:50:02] DEBUG [scripts.scheduled_tasks.snapshot:113] created snapshot at shares/provami/snapshots/snappy_201701171550
[17/Jan/2017 15:51:02] DEBUG [fs.btrfs:713] Quota inconsistency while assigning 0/36559. Rescan scheduled.
[17/Jan/2017 15:51:02] DEBUG [scripts.scheduled_tasks.snapshot:113] created snapshot at shares/provami/snapshots/snappy_201701171551
[17/Jan/2017 15:52:02] DEBUG [fs.btrfs:713] Quota inconsistency while assigning 0/36560. Rescan scheduled.
[17/Jan/2017 15:52:02] DEBUG [scripts.scheduled_tasks.snapshot:113] created snapshot at shares/provami/snapshots/snappy_201701171552
login as: root
root@192.168.11.9's password:
Last login: Tue Jan 17 15:51:33 2017 from 192.168.11.10
[root@rocktest ~]# tail -f /opt/rockstor/var/log/rockstor.log
[17/Jan/2017 15:53:03] ERROR [scripts.scheduled_tasks.snapshot:117] Failed to create snapshot at shares/provami/snapshots/snappy_201701171553
[17/Jan/2017 15:53:03] ERROR [scripts.scheduled_tasks.snapshot:118] Exception while setting access_token for url(http://127.0.0.1:8000): HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /o/token/ (Caused by <class 'socket.error'>: [Errno 111] Connection refused). content: None
Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/scripts/scheduled_tasks/snapshot.py", line 112, in main
    save_error=False)
  File "/opt/rockstor/src/rockstor/cli/api_wrapper.py", line 75, in api_call
    self.set_token()
  File "/opt/rockstor/src/rockstor/cli/api_wrapper.py", line 69, in set_token
    raise Exception(msg)
Exception: Exception while setting access_token for url(http://127.0.0.1:8000): HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /o/token/ (Caused by <class 'socket.error'>: [Errno 111] Connection refused). content: None
```

**Comment by phillxnet** [comment]
https://rockprod.local/ so by hostname and this usually works (KVM name resolution).
https://192.168.124.59/ same no go.
Could you have some token caching going on there?

**Comment by MFlyer** [comment]
Hi @phillxnet actually trying to raise those errors again, sometimes get that snapshot related error sometimes no ?!?

**Comment by MFlyer** [comment]
Add: well, actually that scheduled_tasks error after reboot is normal

Our scheduled tasks (cron) don't have a check for localserver being listening or not, just trying to connect and get a token, we should add granularity with a check (not required, to be considered a plus)
M.

**Comment by MFlyer** [comment]
@phillxnet any news on this???
Now back home, had some reboots and all seem ok both on testing branch & dev env so not able to reproduce it (if needed I can still have a Proxmox rollback to 3.8.16-1 :) )

M.

**Comment by phillxnet** [comment]
@MFlyer I've tried a wipe of the rockstor dir and copied over master and have, from scratch, had similar to report of 'nginx too many start retries' restart issue such as we see in a recent forum post:
https://forum.rockstor.com/t/after-latest-update-web-ui-doesnt-work/2698/7
@schakrava is aware and looking into it.
I haven't had much time to help with this much today unfortunately. My cleanest reproduction, next to fresh build, was the 3.8.16-1.iso install to -7 then reboot case we discussed in the forum. Reboot and time have not sorted my examples of this as per your example. Maybe I've messed up my VM's again but I've seen it in 2 separate ones, and only one of those is my regular dev test machine (the wipe build master variant). Plus we have 3 forum reports now. That's all I've got update wise.

**Comment by MFlyer** [comment]
Well, on my side had only some "on the fly" tests while handling morning backlog (job interviews morning 🎉 ) & only that/this bad PR (sorry @schakrava , it was a "code monkey" coding 😞 )

**Comment by MFlyer** [comment]
Hi @phillxnet can you check this too??
https://forum.rockstor.com/t/after-latest-update-web-ui-doesnt-work/2698/11

Actually first think i noticed was the missing shellinabox config in nginx.conf , then checked nginx.conf.rpmsave that is ok,moved this to nginx.conf and shellinabox back again (my suspicion is an nginx update during Rockstor updates messed up our nginx.conf)
M.

**Comment by phillxnet** [comment]
@MFlyer Yes looks like:
Forum user Christian_Rost found evidence and @schakrava aware. Too late for me to prepare pr though.
https://forum.rockstor.com/t/after-latest-update-web-ui-doesnt-work/2698/10
I removed the None: and was able to get my nuke and pave master build to show first init screen but on each reboot the "None:" before 443 is returned. @schakrava in back channel to us states possible location.

**Comment by MFlyer** [comment]
Hi @phillxnet I think all this related to Rockstor downgrade/upgrade:

check this
```
[root@rocktest ~]# yum history info 9
Loaded plugins: changelog, fastestmirror
Transaction ID : 9
Begin time     : Sat Jan 14 00:53:12 2017
Begin rpmdb    : 505:4fe809fc452006ddbc6a77d4b4a84544ffb65512
End time       :            00:56:04 2017 (172 seconds)
End rpmdb      : 505:7d32c8b2a12c0f3dbd718d7d6d28c1296f05c1cf
User           : root <root>
Return-Code    : Success
Command Line   : downgrade ./rockstor-3.8-14.x86_64.rpm
Transaction performed with:
    Installed     rpm-4.11.3-21.el7.x86_64                      @anaconda/3
    Installed     yum-3.4.3-150.el7.centos.noarch               @anaconda/3
    Installed     yum-plugin-fastestmirror-1.1.31-40.el7.noarch @anaconda/3
Packages Altered:
    Downgrade  rockstor-3.8-14.x86_64   @/rockstor-3.8-14.x86_64
    Downgraded          3.8.16-6.x86_64 @Rockstor-Testing
Scriptlet output:
   1 warning: /opt/rockstor/etc/nginx/nginx.conf saved as /opt/rockstor/etc/nginx/nginx.conf.rpmsave
   2 Running migrations for storageadmin:
   3 - Nothing to migrate.
   4  - Loading initial data for storageadmin.
   5 Installed 0 object(s) from 0 fixture(s)
   6 Running migrations for oauth2_provider:
   7 - Nothing to migrate.
   8  - Loading initial data for oauth2_provider.
   9 Installed 0 object(s) from 0 fixture(s)
  10 Running migrations for django_ztask:
  11 - Nothing to migrate.
  12  - Loading initial data for django_ztask.
  13 Installed 0 object(s) from 0 fixture(s)
  14 Running migrations for smart_manager:
  15 - Nothing to migrate.
  16  - Loading initial data for smart_manager.
  17 Installed 0 object(s) from 0 fixture(s)
  18 systemctl daemon-reload done
history info
```
Can you test if moving nginx.conf.rpmsave to nginx.conf solves?
where you get None I've my IP, but it should be just `listen 443 default_server;` without any address

**Comment by phillxnet** [comment]
@MFlyer But isn't this file re-generated, auto edited, as in my clean build from master my manual edits (removing None:) are un-done after each reboot. So issue exposed by rpm changing the files around but Rockstor scripts should update correctly and that seems to be what's tripping things up. Have I missed something?

**Comment by MFlyer** [comment]
@phillxnet I did not realized that till i deleted nginx.conf and had a reboot, you're right on that

**Comment by phillxnet** [comment]
I have no nginx.conf.rpmsave in my 3.8.16-1 to -7 upgrade demo of the issue.
Also had a quick look at initrock update_nginx() and don't see where the Flake8 changes would have caused this! Got to duck out again I'm afraid (time zone and all). Definitely pretty close we are now though.

**Comment by MFlyer** [comment]
actually initrock rebuilt a perfect nginx.conf file

**Comment by phillxnet** [comment]
If your game to look, src/rockstor/system/services.py looks like it might have the culprit.

update_nginx(ip, port)

around lines 253:254 and on where it's supposed to deal with the None.
The large Flake8 pr changes look like they could account for this behaviour.

If you are still up we can leave what we have found in an issue as it may well get lost in this (now closed) pr. See what you think of the above changes. Looks pretty likely to me.

**Comment by MFlyer** [comment]
Yup, was looking there and agree with you, but actually not able to reproduce it

**Comment by phillxnet** [comment]
My proof all in VMM KVM, looks like it's network sensitive. Sorry got to dash.

**Comment by MFlyer** [comment]
@schakrava leaving you this reference on comments, 1am utc+1, need to rest

**Comment by MFlyer** [comment]
@schakrava & @phillxnet , reading https://forum.rockstor.com/t/after-latest-update-web-ui-doesnt-work/2698/10 last time, that None becomes a string inside nginx.conf

from system/services.py:
```python
            if ((not http_server and
                 re.search('listen.*default_server', lines[i]) is not None)):
                substr = 'listen %s:%d default_server' % (ip, port)
                if (ip is not None):
                    substr = 'listen %d default_server' % port
```
Condition creating a `listen None:443 default_server`:
if not http_server and re then `substr = 'listen %s:%d default_server' % (ip, port)`
next step if ip is not None, we evaluate next if and we get expected `listen 443 default_server` (so my config)
what if ip is None?
first if we get `listen None:443 default:server`
nex ip is not None -> false so we stay with `listen None:443 default:server`

Is that ip == management ip?? never checked this code part

Hope this help
M.

**Comment by MFlyer** [comment]
Reading this today with a clear head: wow, 2am and had that complex/unrequired thinking to say "ehy we have some if statements working wrong way" eheh

**Pull request closed without merging**
