### PR TITLE
pool disk removal wizard shows no disks Fixes #1325

### LINKED ISSUE #1325: pool disk removal wizard shows no disks
To reproduce (current trunk code):
Create a 3 disk raid 1 pool
Resize pool
Remove disk
Expect a table of disk members to be shown but non shown.
Web browser console shows missing handlebars mathHelper.

I have fixed this locally by copying a handlebars mathHelper from another location and will now submit a pr against this issue with my crude fix for review.

### PR DESCRIPTION
**Pull request by phillxnet**
I have build current trunk with this patch set applied and was then presented with a disk table within the remove disk pool resize dialog. I also tested adding and removing a single disk from a 2 to 3 disk raid1 (respectively).
No other testing done I'm afraid as needed this for another pr I'm working on.
Sorry for scant testing and details but seems like a fairly safe (and small) change set.

@schakrava and @priyaganti Submitting for Review.

Fixes #1325

### CODE REVIEW

**Comment by phillxnet** [comment]
@schakrava I am also occasionally getting "Missing helper: "humanReadableSize"" in console on this same screen so I can add that as well to this pr just in case, will no so now directly.

**Comment by phillxnet** [comment]
This now seems to be reliable showing the expected table in the wizard dialog when removing disks.

**Comment by schakrava** [comment]
Thank you @phillxnet. Nicely done!

**Comment by phillxnet** [comment]
@schakrava Cheers.

**Pull request merged**
