### PR TITLE
Issue #1515

### PR DESCRIPTION
**Pull request by tomtom13**
This will just remove a line that was committed by @MFlyer in commit 1e5e6fd07002ddbdc9fc199869f2deade06fead2

I know that there might be a better sollution, but I don't know this code and personally I would preffer to concentrate on networking config. 

Also without this, it's impossible to setup samba on new machine (because it will not accept anny settings and will not punch in any default in either)

### CODE REVIEW

**Comment by MFlyer** [comment]
Hi @tomtom13 ,
actually there's #1496 to be merged / not yet merged that solves this

Mirko

**Comment by tomtom13** [comment]
Ok, when I'll get home I'll give it a whirl.

Anyway I've notice that your samba commits are mostly geared at users with active directory etc ... when pushing this direction, would it be possible for you to give options to users like "security = share" through combo box ? Not every rockstor user uses it's box in multi-user setup, and they would like as simple as possible setup. 

Don't get it wrong, we all do stuff that server us the most, just let's not alienate group of users by that.

**Comment by tomtom13** [comment]
Since @MFlyer has an update for that I'll close that one.

**Comment by MFlyer** [comment]
Hi @tomtom13 ,
actually had code more on AD side of Samba because that was the faulty one, but `security = ads` runs only on AD integrated Rockstor, while having default `security = user` on a normal samba environment (https://www.samba.org/samba/docs/man/Samba-HOWTO-Collection/ServerType.html#id2559114)
Obviously we can move to a select (security = user || share) or have a different approach via #1481 (moving acls to share creation & have security = user ??)

**Pull request closed without merging**
