### PR TITLE
abstract by-id device path in a function

### PR DESCRIPTION
**Pull request by KaiRo-at**
As discussed in PR #1704 this is an updated version of the patch there, reworked on top of current master.
This patch abstracts away the actual /dev/disk/by-id/ path substitution into a function, grouped with similar function in osi.py.
This would help us at Minebox to stay closer to upstream.

### CODE REVIEW

**Comment by schakrava** [comment]
Can one of the admins verify this patch?

**Comment by schakrava** [comment]
Can one of the admins verify this patch?

**Comment by phillxnet** [comment]
@KaiRo-at hello again.
@schakrava I can take a look at this, but not directly unfortunately. Hopefully soon though.

**Comment by schakrava** [comment]
LGTM. Thanks @KaiRo-at

**Pull request merged**
