### PR TITLE
Issue#1290 password recovery system via web ui

### PR DESCRIPTION
**Pull request by MFlyer**
#1290 PR ready for review.

Hi @schakrava, here is my working Password recovery system via Pincards.

Actually it's like this:

- Every managed user and root user can have a Pincard for password reset
- Root user (or generally uid 0 user) password reset requires OTP confirmation too (Email alerts enabled and one time password sent to admin mail, to be added to required pins)
- Users are shown Pincard only one time, no way to recover a Pincard (every click for Pincard means a new Pincard generated)
- Pincards are in ID-1 format (or at least like ID-1 format), generated via html5 canvas and can be saved as png image or via text table (avail under Pincard image)
- "Reset password" box on login page with all info has been extended with Pincard reset, give it a try (it's easier than explain it :smile: )
- Password reset nicely tested and working on managed user, managed user with webui access, root user

Note: obviously for OTP reset on root user we assume all email settings are right!

Mirko

### CODE REVIEW

**Comment by MFlyer** [comment]
Cross reference to #1357 - Mods over data_collector

**Comment by MFlyer** [comment]
Hi all, to @schakrava : sorry for messing #1290 with tons of commits, but i was testing rebase over latest mods in Rockstor master.
Actually this branch is happy with rockstor-core master and could be merged.

Done rebasing to current state of 2 jul 2016 considering it'll be required again after @phillxnet PR merged (both PR have modified data_collector)
 
Flyer

**Comment by schakrava** [comment]
Beautifully done @MFlyer! I can tell you had fun implementing this feature. I've enjoyed reading your code(thanks for useful comments) and testing it. I especially liked the following

* You've made it super secure by not giving out information beyond the minimum necessary to a potential hacker.
* pincard image with rockstor logo as the background!
* Clean and beautiful UI bits
* OTP for root user is awesome! no more tedious reset for proactive but forgetful users like me :)

**Comment by MFlyer** [comment]
Hi @schakrava thanks, this PR was really fun :smile:

**Pull request merged**
