### PR TITLE
fixes #1410 - Added missing js dependency

### LINKED ISSUE #1410: Email Alerts page missing dependency
To @schakrava : starting from the title, issue related to missing dependency over latest mods (submit not working)

Flyer

### PR DESCRIPTION
**Pull request by MFlyer**
@schakrava Finally solves missing dependency over #1410 - Email Alerts

Tested, just need merge

Flyer

### CODE REVIEW

**Comment by phillxnet** [comment]
@MFlyer Just a little nit pick here but it looks like we are all accidentally popping in tabs by accident occasionally. Just mentioning as @schakrava has picked me up on the same in the past. I believe the project convention is only spaces (usually in groups of 4 but some old files use only 2) but no tabs.

Well done on taking owning of this one by the way, and the quick fix.

**Comment by MFlyer** [comment]
Hi @phillxnet had it "on the fly" so probably with wrong tabs! :/

**Comment by schakrava** [comment]
looks good @MFlyer . Thanks for taking care of this. I should've caught this in the first place :)

**Comment by MFlyer** [comment]
No problem @schakrava , to be honest i thought jslibs were managed something like js views -> rockstor.js (dependencies solved/script tags added on build process), so now I've learned how to handle it ;)

**Pull request merged**
