### PR TITLE
Fixes a small samba service regression 

### LINKED ISSUE #1495: Small Samba regression
Hi @schakrava , reference to this forum thread:
https://forum.rockstor.com/t/error-running-a-command-cmd-at-samba-share-screen/2224/25?u=flyer

### PR DESCRIPTION
**Pull request by MFlyer**
To @schakrava , sorry again, on dev env had no null field over ad config :/

Fixes #1495

Ready to merge before stable release
M.

### CODE REVIEW

**Comment by MFlyer** [comment]
To @schakrava, updates after solving with forum user: both this and #1492 can be merged, user issue not on Rockstor (uefi bios + r8169 driver card having nic up/down, moving to legacy bios solved it :smiley: )

M.

**Comment by tomtom13** [comment]
Fixes #1515

**Comment by tomtom13** [comment]
@schakrava can we expedite this pull ? I've tested a 3.8.15 without this fresh out of the box (and also after updating it it .1) and result is that one can NOT setup a successful samba session. Samba is running but one can not get to a share from windows machine either using guest or actual user account because master samba settings are not set correctly !!! (the workgroup bug block the rest defaults to be stored in samba config)

**Comment by MFlyer** [comment]
Hi @tomtom13 if you need it's just a 1 line code on `src/rockstor/smart_manager/views/samba_service.py`, having a reboot after changes should make it work on testing/stable env too! :)

**Comment by tomtom13** [comment]
@MFlyer it's not about me, I know how to patch my box :P it's about normal users, right now anybody installing rockstor will fail to install samba and for 90% home users it's a deal breaker if they can't have samba.

**Comment by MFlyer** [comment]
Hi @tomtom13 I know you can do that :P My #1459 probably was a damned premonition to this :disappointed: 

@schakrava @phillxnet & @sfranzen I believe we seriously have to handle "missing important patches":
my idea with #1459 is to have something requiring user interaction (have a form where users insert PR number then autopatch), but that forces user to manual intervention.
Suggestions? Can we have urgent PR merged and released on stable channel too?? not sure about that.
@schakrava can we add a new ad hoc yum repo just for emergency patching (so doing we won't have a new release like 3.8.15-1 or similar)

**Comment by schakrava** [comment]
@MFlyer and @tomtom13 . Thanks for this important discussion. I wish we merged this before 3.8.15, but it's too late now. There are a few takeaways from this experience. 1) Let's test our stuff thoroughly, and especially for backend, please add tests going forward. @phillxnet has added a bunch of them recently you can use as a reference to get up to speed on that. 2) I need to do a better job as part of our pre-stable release testing and you are right, a personal note about this regression would have helped, but I could've looked as well; shit happens. 3) Since the fix is so small, we can have it as "errata" for now. I am not in favour of pushing hot-fixes into stable. We can also put a console script that can pull an arbitrary gist and make hot-fixes easily applicable.

**Comment by schakrava** [comment]
oh, finally @MFlyer thanks for the fix and sorry couldn't merge it fast enough :(

**Pull request merged**
