### PR TITLE
Issue#998 dashboard crashes if opened long - Cpu Widget - Part 1

### PR DESCRIPTION
**Pull request by MFlyer**
Hi @schakrava :smiley:  ,
this is a Part 1 of X PR to move dashboard widgets from SVG to CANVAS (#998) with Chart.js (not all widgets, only where really required).

This PR ready to merge, going to work on Network Widget (Probably our Black Beast with client cpus because of huge amount of data & svg)

Pls check also rockstor js lib PR to add chart.js

Flyer

### CODE REVIEW

**Comment by MFlyer** [comment]
Note: checked and network widget already using canvas with jQuery Flot, so that should be ok with performance.
Anyway moving it to Chart.js

Flyer

**Comment by MFlyer** [comment]
While coding on network widget and having Rockstor dashboard freezed found this:

- Shares & Pools widgets can be moved to simple boostrap progrebars
- Capacity, allocation and usage widget can be a horizontal bar chart.js chartbar
- Current cpu killer widget is memory widget (tons of updates with d3.js SVG drawing)

Working on it, hope to open new PRs asap :smiley:

**Comment by sfranzen** [comment]
How do you get the dashboard to freeze?! :stuck_out_tongue: I still haven't had that happen.

I'm currently trying to get the PatternFly interface stuffed into a separate page, to make it possible to work/experiment on it without bombing the UI. They have some very pretty (bootstrap) progress bars.

**Comment by schakrava** [comment]
@MFlyer I really like where you are going with this. The graph however doesn't move smoothly as the current version. It seems to update once a second. Have you noticed that? I suppose it should be possible to smooth it out?

I noticed that the font is not as sharp as before. Not a big deal, but wondering what made you change it.

**Comment by MFlyer** [comment]
Hi @schakrava, perfectly know about charts not animating smoothly and had some checks/talks on chart.js github page too ( [https://github.com/chartjs/Chart.js/issues/3126](url) )
Found this morning (LOL) a merge about this : https://github.com/chartjs/Chart.js/pull/3399

Please wait  merging, going to add new chart.js lib and check it, or manually patch it :wink: 

> I noticed that the font is not as sharp as before. Not a big deal, but wondering what made you change it.
I'll check it!

**Comment by MFlyer** [comment]
Hi @schakrava ,
finally had a cloned Chart.js repo and built it on gulp with latest PRs adding smoth charts.
Tomorrow going to have some tests and let you know!
Mirko

**Comment by MFlyer** [comment]
Updates after testing: got desired behaviour just adding an animation easing over graph (linear easing is the good one), but still having charts time ticks not nicely sliding: animation runs only on chart data and not on scales.

**Comment by sfranzen** [comment]
@MFlyer,
Maybe it's an idea to just make the horizontal axis static? I think it's clear enough if you label the axis "1 minute ago" and "now" at the ends, or with negative values like "-1:00, -0:30, 0:00".

**Comment by MFlyer** [comment]
Hi @sfranzen , my heart reaction : yes, I thought of that solution too, but that is the "easy way" and I'd like to have a nice sliding chart :smiley: 
Here on chartjs/Chart.js#3425 having a talk about this, maybe finally I'll contribute over Chart.js to eheh

**Comment by schakrava** [comment]
Thanks @MFlyer . It looks slightly smoother. But I really appreciate the perf benefits behind the scenes with this new approach, and also readability/maintainability of code. I think it's a good time to merge this pr and continue working on any more improvements in subsequent ones.

**Comment by MFlyer** [comment]
Hi @schakrava , going to have some minor improvements on all charts, so will have a small patch over Cpu too :)

Important: Did you merge/add new chart.js lib ??? Asking because rockstor/rockstor-jslibs#5 seems not merged

**Pull request merged**
