### PR TITLE
File sharing initialism inconsistencies. Fixes #2117

### LINKED ISSUE #2117: Inconsistencies with File Sharing page initialisms
Another minor issue...

The NFS, AFP and SFTP pages all use lower case for their initialisms when no share has been defined, for example: 
image
 These should be in uppercase which would keep them consistent with the rest of the page

### PR DESCRIPTION
**Pull request by jonpwilson**
- Changed 'afp' to 'AFP'
- Changed 'sftp' to 'SFTP'
- Changed 'nfs' to 'NFS'

Fixes #2117

### CODE REVIEW

**Comment by phillxnet** [comment]
@jonpwilson Thanks for yet more user facing text improvements. These are nice additions that help lend more of a polish and have gone unnoticed/uncorrected for quite some time now.

Cheers, and much appreciated.

Merging now to try and keep up with your pull requests.

**Comment by jonpwilson** [comment]
Damn, you beat me to it - I'd made the changes on the web, just logged on to my machine to squash them to see it's been merged! Will be cleaner next time ;)

**Comment by phillxnet** [comment]
> I'd made the changes on the web, just logged on to my machine to squash them to see it's been merged!

@jonpwilson  Hello again. I'm a little confused, are you meaning to comment on another issue. I've left #2119 open as there was another instance of latest that I missed. Or are you referencing the 3 commits not being squashed. As you were a new contributor, to this project at least, I didn't wan't to bother you with any more formalities re the squashing.

On more complex pull requests I often look for the "ready for review" text, and @FroggyFlox often maintains pull requests in draft mode to avoid them being merged accidentally. I was just a little concerned about getting behind and then having to deal with merge conflicts, or holding up other committers. We have a couple of older pr's that I'll tend to now that the majority of yours are merged. Let me know in your remaining #2119 what you want to do there.

Thanks again and apologies for messing you around re potentially merging before it was appropriate. Looked good to me though :).

**Comment by jonpwilson** [comment]
> Or are you referencing the 3 commits not being squashed. As you were a new contributor, to this project at least, I didn't wan't to bother you with any more formalities re the squashing.

Sorry, it's me creating more confusion - I was referencing the above, 3 commits when they weren't necessary. I should have added a draft label, apologies. 
 
> On more complex pull requests I often look for the "ready for review" text, and @FroggyFlox often maintains pull requests in draft mode to avoid them being merged accidentally. 

Ahh, good to know - I'll do that in future.

And now I'll stop adding to an already closed PR :)

**Pull request merged**
