### PR TITLE
Issue #1263 rfc2307 active directory

### PR DESCRIPTION
**Pull request by MFlyer**
PR on issue #1263
To @schakrava : tested on my AD and easily switched between Rockstor default and RFC2307 and viceversa

Not able to check rfc2307 grabbing UIDS shells and homes because my AD hasn't been provisioned with rfc2307 (and i can't modify it on the fly, my AD serves 50+ working users - not a test env)

Maybe @ScarabMonkey can give it a try :wink: 

Apart from that, i can safely say that with rfc2307 enabled and AD missing rfc2307, Rockstor still get users and groups providing valid uids without generating any kind of error

Flyer

### CODE REVIEW

**Comment by schakrava** [comment]
@ScarabMonkey Any chance you can test this branch?

**Comment by ScarabMonkey** [comment]
This seems to work as advertised - users and groups do indeed get their UID/GID from the Active Directory when the box is ticked.

**Comment by MFlyer** [comment]
@schakrava can we merge? :smiley:

**Comment by schakrava** [comment]
Thanks @MFlyer and @ScarabMonkey! Pleased to merge this pull request.

**Pull request merged**
