### PR TITLE
Issue#1340 field validation email setup

### PR DESCRIPTION
**Pull request by MFlyer**
Hi @schakrava this solves #1340 

Thinking about our validation plugin i thought easy to add a pattern rule, but it's on additional methods package (added via rockstor jslib PR).

Over being the fast & easy solution for this issue, I think pattern ruler can be useful for all developers :)

Flyer

### CODE REVIEW

**Comment by schakrava** [comment]
Thanks @MFlyer ! looks good

**Comment by schakrava** [comment]
hi @MFlyer . There is a minor conflict in email.jst and email.js. Could you please rebase or open a new clean pull request for this?

**Comment by MFlyer** [comment]
Hi @schakrava , rebased, here we go :wink:

**Comment by schakrava** [comment]
Thanks @MFlyer !

**Pull request merged**
