### PR TITLE
Moving Disks smart custom icon label to top position

### PR DESCRIPTION
**Pull request by MFlyer**
Hi @schakrava , another small issue fixed:

main code is on line 67 disks.js (others are code cleaning/beautify)

Ready to be merged :wink: 

Ref #1565
Mirko

### CODE REVIEW

**Comment by MFlyer** [comment]
cross ref to @phillxnet for his big task on disks role (conflicts over files)

**Comment by phillxnet** [comment]
@MFlyer Thanks for the heads up. Yes I'm making some fairly large changes to the disks_table.jst but currently those changes are constrained to the first column entries and their associated icons and links. And in disks.js I'm adding a bunch of extra handlebar helpers.

Cheers and well spotted (I'm getting there though :) ).

**Comment by schakrava** [comment]
test

**Comment by schakrava** [comment]
Thanks @MFlyer and @phillxnet

**Comment by MFlyer** [comment]
Cheers @schakrava :)

**Pull request merged**
