### PR TITLE
Issue#1278 services config as modal

### PR DESCRIPTION
**Pull request by MFlyer**
Hi @schakrava & @priyaganti ,
this PR is ready to review/merge.

Had it because found it on Looney Bean and quite easy to solve :)

This is how I got modals without full rewriting of views:
- changed router configureservice to open a modal instead of moving maincontent to view
- added some hacks to grant switch on x/cancel buttons / submit successful from modal back to services (app_route.navigate with no trigger)
- resized configure_SERVICENAME templates to better fit on modals

Mirko

### CODE REVIEW

**Comment by sfranzen** [comment]
@MFlyer I also wanted to use plenty of modal dialogs for my snapper view, so I coded [this](https://github.com/sfranzen/rockstor-core/blob/snapper/src/rockstor/storageadmin/static/storageadmin/js/views/common/bootstrap_modal.js) "backbonified" dialog that works like this:
```
HTML:
<div id="myModal"></div>

Inside a Backbone view:
var dialog = new ModalView({
    el: this.$('#myModal'),
    template: window.JST.my_modal_content
}).render();
dialog.once('submit', this.mySubmitHandler, this);
```
It is

**Comment by MFlyer** [comment]
Hi @sfranzen, had same idea about a new modal view (if I'm not wrong there's an existing backbone plugin too), so let's check it also with @priyaganti.
My suggestion about adding a new view : check current Rockstor view to avoid missing parts :)
M.

**Comment by MFlyer** [comment]
Add for @sfranzen : 
for a better coding/code structure the new view should be on `src/rockstor/storageadmin/static/storageadmin/js/rockstor.js` , becoming globally available.

If job won't kill all my time, I'll check it today :)
M.

**Comment by MFlyer** [comment]
Hi all,
added a new #1501 issue for a common Rockstor Modal View on 3.8-16 roadmap, so meanwhile we can marge this and have some good testing on next cycle

M.

**Comment by sfranzen** [comment]
@MFlyer Should it? I mean I don't really mind, but since all of our JS is in the global scope, I personally find it a little clearer to have them in the `common` section, which is added to the JS output before the rest of the views.

**Comment by MFlyer** [comment]
Hi @sfranzen :smiley: 

Just to let you better understand my idea: check rockstor.js code, my idea is to extend a Rockstor view instead of the generic backbone view, so we inherit some defaults too (fetch, etc etc).
We can do this in common subfolder or directly in Rockstor (my idea: better in rockstor.js to have it on top of all)
M.

**Comment by schakrava** [comment]
@MFlyer modals are looking nice! Upon testing, I noticed a minor glitch. For example, follow these steps. 
1. turn off rock-on service if it's previously on.
2. configure the rock-on service. (doesn't matter even if it's preconfigured, just submit on modal)
3. turn the service on again. You'll notice that the switch slightly shifts to the left as expected, but after a few seconds, when the listener gathers the update of all services, it should line up with rest of them. This update is not happening. There is a helpful error in the console. This screenshot might help.

rock-on_service

Could you please fix it? Also, you should rebase to merge @phillxnet 's nut_configure template changes.

**Comment by MFlyer** [comment]
@schakrava :+1:  will check it asap

**Comment by MFlyer** [comment]
PR rebased over last Phil PR, tomorrow going to check glitch!

**Comment by MFlyer** [comment]
First update: find out that with new modal config pages websockets get disconnected, checking this too (maybe partially related to that glitch)

**Comment by MFlyer** [comment]
Great @schakrava , your attention to that glitch made me find this #1522

Solving over python-socketio migration :)

**Comment by schakrava** [comment]
@MFlyer are you still working on this or is it ready for me to test and merge?

**Comment by MFlyer** [comment]
@schakrava ready to test & merge, sorry had my ok go on PR :)

**Comment by schakrava** [comment]
Thank you @MFlyer . Looks great now!

**Comment by MFlyer** [comment]
Thank you @schakrava ,
I was feeling uncomfortable having Rockstor messed up because of previous wrong PR with some pieces from modal :)

**Pull request merged**
