### PR TITLE
drive power down interface. Issue #885

### PR DESCRIPTION
**Pull request by phillxnet**
Opening this pull request to aid in collaboration.

The last issue I'm having problems with in this pr is the passing of an additional value 'spindown_message' from:

storageadmin/static/storageadmin/js/templates/disk/spindown_disks.jst
and it's associated js in
storageadmin/static/storageadmin/js/views/spindown_disks.js

The value is the index in the js object "spindownTimes" in spindown_disks.js that the 'display_spindown_time' handlebar helper in the same file uses to populate the form drop down named spindown_time.

So I want to pass as an additional value the text (key in js object) used to populate that drop down.
The selected value is already passed successfully I'm just stuck on adding the text of the selected key as an additional element.

The receiving  method in:
storageadmin/views/disk.py
def _spindown_drive(cls, dname, request):
has in place a request.data.get('spindown_message', 'message issue!'))
and passes this on to:
set_disk_spindown(disk.name, spindown_time, spindown_message)

So stuck on presenting the js object key as spindown_message.

Everything else is currently working as intended.

Sorry if this is a silly one it's just the last hurdle and I'm drawing a blank.

### CODE REVIEW

**Comment by schakrava** [comment]
I reviewed briefly and your changes are looking great @phillxnet!

One way to pass the key is to assign spindownTimes to _this to make it available inside the submitHandler.
`
_this.spindownTime = spindownTimes
`  
After you get the json from the dom 
`_this.$('#add-spindown-disk-form').getJSON()`
you can lookup the key of corresponding spindowntime value the user selected, which is in that JSON and update the JSON by adding a new key, value pair with message. Hope that helps.

Btw, should this feature apply to non rotational media at all? I am guessing not. If so, does your code detect that and disable it automatically?

**Comment by phillxnet** [comment]
@schakrava Thanks, that was just the job and worked perfectly.
I've committed it in https://github.com/rockstor/rockstor-core/pull/1260/commits/c70980dbf6a6528c83bd8b8d5fb936a15546a3ce

Another quick question at your leasure:-
How do I set the background colours of the d3 slider (screen shot):
slider-background-colours-not-showing

The ranges are indicated in the key below the slider and can be hardwired but can't see where to do it.
Thanks and sorry if this is another silly one.

**Comment by phillxnet** [comment]
@schakrava Don't worry about my last background colour question; I've made some headway via:-
d3.slider2().......reclaimable(127).used(1)
So I'll keep chipping away on this one and let you know when it's ready for review.

**Comment by phillxnet** [comment]
Current progress with Disks table for drive Spindown and APM status (screenshot):
disk-spindown-time-and-power-in-table

**Comment by phillxnet** [comment]
- [ ] Set slider to reflect current APM value when loaded
- [ ] add text box input validation (ie only numbers from 0 - 255)
- [ ] Update slider on text box input.

**Comment by phillxnet** [comment]
- [ ] Resolve false positive on TS32GMSA370 for is_rotational - an msata with acoustic management !!! Which I have used as an indicator of rotational nature.
- [ ] Final UI tweak to deal with showing but not setting APM values unless specifically enabled. Involves configuring the "Enable APM settings" tickbox and possibly intervening on values represented by the associated controls.

**Comment by phillxnet** [comment]
@schakrava Almost there now, just need to be able to disable the d3.slider2 ie
this.$('#slider').attr('disabled', 'true');
doesn't do it.
But the same works on the associated text box, ie refuses to take external input.
I need it to present it's value but not allow input, ie no longer respond to drags. Don't see a call / setting for this though.
Cheers.

**Comment by phillxnet** [comment]
This is now mostly functional except for an input validation bug caused by contention between the text box updating the slider first rather than triggering the validation routine. Will have another look shortly.
Quick screenshot of the config screen as is:-
spindown-config-page

**Comment by phillxnet** [comment]
I have re-based this branch on the just released 3.8-13 master branch and to avoid replication of commits I deleted the github remote branch which closed this pr. I will open a new pull request shortly based on the new branch.

**Pull request closed without merging**
