### PR TITLE
Update rockon.py - only load files with a .JSON extension

### LINKED ISSUE #2473: Don't load non-json rockon config files?
This happened on 4.5.4-0.

I have added `omada-controller.json` to the usual place in order to install it as a rockon via WebUI. Because I make a lot of amendments during testing, my text editor creates a backup file to the same dir but appends a tilde: `omada-controller.json~`

I have found that when clicking the Update button in WebUI, an arbitrary file is chosen from that dir. Sometimes with the tilde, sometimes without.

I suggest that you search for more specific rockon config files. E.g. that they end with, and only with ".json".
Of course, it is my duty to make sure only one, valid JSON rockon config file is in that dir, but I thought I put up the issue up for discussion anyway.

I'm confident that this can be repro'd by placing any two .json and json~ files in the dir.

1674120763716 - Copy

### PR DESCRIPTION
**Pull request by Stitch10925**
Filter out any non-JSON files from the local repo

https://github.com/rockstor/rockstor-core/issues/2473
Fixes #2473

This PR was re-applied from a PR in the master branch:
https://github.com/rockstor/rockstor-core/pull/2480

@FroggyFlox 
This time on the testing branch!

### CODE REVIEW

**Review by FroggyFlox — APPROVED** [review]
As in #2480: 
I just tested this PR in a VM: works as intended.

- any file in the local_metastore that ends in *.json is correctly parsed.
- renaming that file to *.json.backup and the file is ignored.
- switching back to current testing branch and the *.json.backup file is not ignored anymore and parsed.

**Unit tests**
```
buildvm:/opt/rockstor # cd src/rockstor/&& poetry run django-admin test
Creating test database for alias 'default'...
Creating test database for alias 'smart_manager'...
System check identified no issues (0 silenced).
............................................................................................................................................................................................................................................
----------------------------------------------------------------------
Ran 236 tests in 14.090s

OK
```

Looks all good to me!

**Comment by FroggyFlox** [comment]
@Stitch10925 , thank you for putting up with the branch change and my apologies for such a request for this change.

@Stitch10925, @phillxnet, this PR does exactly what it is intended to do so I think it's a no brainer. It does highlight a shortcoming in our approach though as we indeed focus more on the file extension that the actual format of the file. 
We should think of also expecting incorrectly formatted json files here, especially given this directory may be used by users to develop their Rock-on json file. Currently, we fail the entire "Update available Rock-ons" process just because one file was incorrect. I think it might be good to only fail that particular file and not everything in such situation. Of course, we would need to implement this once we have a better way to surface this sort of information in the UI (probably post #1877) otherwise it may seem like nothing happened. Just a quick thought...

@Stitch10925, thanks again!

**Comment by FroggyFlox** [comment]
Note this issue would also fix #2349.

**Comment by phillxnet** [comment]
@Stitch10925 Thanks from me also for this work, much appreciated.
@FroggyFlox Thanks for the thorough review, also much appreciated.

I'll go ahead and merge so this ends up in the pending 4.5.6-0 testing rpm builds.

My apologies for the delay here, I've had some background dealings to deal with unfortunately.

**Pull request merged**
