### PR TITLE
Remove special treatment for the deprecated discourse rock-on #2033

### PR DESCRIPTION
**Pull request by phillxnet**
If anyone wishes to restore our discourse rock-on and use this removed code as a template then we have it preserved in git so we can safely remove for now to avoid future confusion and avoid carrying dead code.

## Testing:
No additional test failures.
Source build (Leap 15.3 JeOS base) was able to establish the rock-on system then install-&-run/stop/start/stop/uninstall the netdata rock-on. Then stop and start the Rock-on service successfully there after.

### CODE REVIEW

**Comment by phillxnet** [comment]
@FroggyFlox Although this may affect existing users of our discourse rock-on I'm not keen to keep otherwise dead code around. Especially give the almost complete lack of feedback on this particular issue. And that given we are moving to the next stable release we need to remove code that is not longer supported. I'm guessing that if we do have any long term users of our discourse rock-on,having installed it long ago when  the image was retrievable, that they have similarly done their own management of that container.

It's also a burden for us to carry too many 'special' cases and I think it would be good to remove all the cases of such special treatment that we can. Especially as we move to having to migrate all our code to Python 3.

**Comment by phillxnet** [comment]
A source build post this change was also tested against our rock-on registry post discourse removal and no errors were observed.

See partner issue: https://github.com/rockstor/rockon-registry/pull/299

@FroggyFlox given this is essentially removing dead code I think we can safely merge.

Caveate: Existing users of our depricated/removed discourse rock-on should still have the ability to remove the rock-on as our fail through functionality should allow for this. Enabling those users to 'clean-up' and move to fully a self managed discourse arrangement outside of the Rockstor Web-UI. With the remnants of it's install also removed. No share content will have been affected by this, only the image removal.

**Comment by phillxnet** [comment]
@FroggyFlox I'll go ahead an merge this to avoid it growing too old to merge. Testing looks to have been fairly comprehensive.

**Comment by FroggyFlox** [comment]
Sorry for dropping the ball on this one and never getting back to you.

**Pull request merged**
