### PR TITLE
Issue#673 kvm virtio drive serial

### PR DESCRIPTION
**Pull request by phillxnet**
Patch to provide an additional mechanism to retrieve drive serial numbers.  Currently only seems necessary for virtio drives as lsblk fails to retrieve their serial which we need.  So when existing mechanisms fail to get a drive serial this patch tries again with for example a cat /sys/block/vda/serial.
This entry seems not to exist with other drive types and we have a fail through to return an empty string if no serial entry is found so (hopefully) no worse off anyway if accidentally called with another device type.
Should only be called when existing mechanism fails to get a serial for a block device listed in lsblk.

N.B. does not address the issue of being able to install on a vda (rather than an sda) device.

### CODE REVIEW

**Comment by phillxnet** [comment]
Fixes issue #673

**Comment by schakrava** [comment]
@phillxnet Big thank you for opening this pull request and sorry it took a bit longer than I wanted to provide feedback. A couple of comments

1. Indentation seems a bit off, perhaps your tab is mapped to 8 spaces? You can see this on lines 48-49 in btrfs.py and a few other places. Can you change it to 4 spaces and reformat?

2. in get_virtio_disk_serial function, is there any particular reason for using the cat command instead of programmatically checking the existence of the file and reading it like so:

import os
dev_path = ('/sys/block/%s/serial' % device_name)
if (os.path.isfile(dev_path)):
    with open(dev_path) as dfo:
        for line in dfo.readlines():
            # parse the contents and extract serial number

3. Can you attach a sample output of cat /sys/block/vda/serial ?

**Comment by phillxnet** [comment]
@schakrava Thanks for the review.

Ok, yes sorry about the indentation.
1:
I am set to 4 spaces here +4 more for continuation lines. Seems there was an interplay between existing indents and (in one case re-occurring) additional auto indents.
The additional patches should address this, your noted example was a result of the auto-indenter grouping like with like.  I have re-formatted slightly there and that seems to have sorted things.
Should at least be more consistent now than it was before.
2:
re: reasoning of cat
I was originally going to use "udevadm info /sys/class/block/vda"
but then found that eg cat /sys/block/vda/serial gave us directly what we were after so seemed like the most direct path with the added bonus of an error code / dealing with the non existence.
ie a sample output of the cat command in this context via a ssh:-
answers your 2.1
```
[root@rockstor ~]# cat /sys/block/vdc/serial 
12345678901234567890[root@rockstor ~]#
```
So as can be seen its offered up on a plate so I went with it.
2: (some more reasoning)
Seemed like the simplest solution as then no file handler and iterator and loop were needed to get at something that we could just get directly with a single native (and hence quick) command.  I know there may be the overhead of firing up a whole shell to get this command but there is going to be similar 'weight' behind the scenes in the cross platform file system access; only this way we can more easily see what happens as less code.

If you would prefer that we avoid this cat method then I can re-write with your suggestion but it seems heavier to me.  I was also aware that in the shell the cat command has always returned special files just fine but other file opening programs have on occasions failed with special files; leading me superstitiously I admit, to the simple and I though clean solution. Especially given the pre-existence of your run_command. Sorry no examples to hand of special file access failure.

Would you like me to re-write it?

**Comment by schakrava** [comment]
@phillxnet your reasoning for cat sounds fair enough, thanks for explaining it. My tendency is to use python if I can, but that's just me. no need to re-write your code. one other thing popped out with regards to return str(out)[2:-2] . since out is a list where the first element is our serial number, you can just return out[0] . It's a trivial change and because I am closing out for the release update, I made that change myself and merged. See you in the next pull request and thanks again!

**Pull request merged**
