### PR TITLE
Add support for mounting devices to Rockons. Fixes #1957

### LINKED ISSUE #1957: Add support for mounting a particular device in Rockon
I've been interested in trying to help improving the functionalities of the Rockon system following several obstacles I've encountered (multiple containers, custom `docker run` command argument, other `docker run` options) for a while now, but never dared digging through the code. 
Recently, however, I started looking into taking advantage of a new functionality of the EmbyServer container: hardware transcoding. Unfortunately, this would require the RockOn to support the `--device` option to `docker run`. 

As mentioned in the corresponding issue (https://github.com/rockstor/rockon-registry/issues/152), I was thus thinking to implement support for a new _**Devices**_ object in the JSON files. This object would follow the same structure as the _**Environment**_ object, with `"description"` and `"label"` fields in the JSON file triggering a new page in the Rockon install wizard for the user to input a custom device path (`/dev/dri/renderD128` for instance).
```
{
  "description": "path to hardware transcoding device (/dev/dri/renderD128)",
  "label": "VAAPI device"
}
```

I started working on it and modify the files I believe are involved in such a process (https://github.com/FroggyFlox/rockstor-core/tree/RockOn_device_option), but am hitting an obstacle in figuring out what's wrong. The problem I'm facing is that I do not get the Rockon install wizard to open a new page related to the _**Devices**_ object I'm trying to implement.

While I can read and understand more or less the intent behind the Python code, I am not familiar enough with Javascript to even understand whether my issue lies first in the frontend or backend. 

Would anyone be kind enough to offer some pointer(s)?
I've been testing the following changes:
https://github.com/FroggyFlox/rockstor-core/tree/RockOn_device_option

With the following JSON file:
https://github.com/FroggyFlox/rockon-registry/blob/emby_dotNET/embyserver.json

### PR DESCRIPTION
**Pull request by FroggyFlox**
Fixes #1957 
Add support for the docker run `--device` option to Rockons to allow users to add custom device(s) to their Rockon(s), based on the existing support for the docker run 'environment' variables. This PR is now functional and ready for feedback and review.

Briefly, this PR adds support for a new **"devices"** object in Rockons' json definition files, following the same structure as for the **"environment"** variables with "description" and "label" fields in the JSON file (see below).
```
{
  "description": "path to hardware transcoding device (/dev/dri/renderD128)",
  "label": "VAAPI device"
}
```

This, in turn, triggers the Rockon install wizard to create a new **Device Choice** page, with as many free text input fields as devices listed in the JSON file. The text input in these fields is then validated under the following rules:
1. optional: if blank, validate.
2. if filled, the input must begin with '/dev/' and only contain alphanumerical characters (thanks @phillxnet  for your regex definition).

Testing:
All changes in python files pass Flake8.
The style of the `rockon.js` file was fixed by ESLint following style settings described in the `.eslintrc.js` file in the rockstor-core repo.
The JSON file used for testing is the following, with 3 optional devices listed:
https://github.com/FroggyFlox/rockon-registry/blob/emby_dotNET/embyserver3devices.json

### CODE REVIEW

**Comment by schakrava** [comment]
Can one of the admins verify this patch?

**Comment by schakrava** [comment]
Can one of the admins verify this patch?

**Comment by FroggyFlox** [comment]
The storage admin migration file present in the original commit was replaced by the correct one as the initial one corresponded to an older incremental migration.
This file was created and applied as follows:
```
[root@rockdev ~]# /opt/build/bin/django makemigrations storageadmin
Migrations for 'storageadmin':
  0005_auto_20180913_0923.py:
    - Create model DContainerDevice
    - Alter unique_together for dcontainerenv (0 constraint(s))
    - Alter unique_together for dcontainerdevice (1 constraint(s))

[root@rockdev ~]# /opt/build/bin/django migrate storageadmin
Operations to perform:
  Apply all migrations: storageadmin
Running migrations:
  Rendering model states... DONE
  Applying storageadmin.0005_auto_20180913_0923... OK
The following content types are stale and need to be deleted:

    storageadmin | networkinterface
    storageadmin | poolstatistic
    storageadmin | sharestatistic

Any objects related to these content types by a foreign key will also
be deleted. Are you sure you want to delete these content types?
If you're unsure, answer 'no'.

    Type 'yes' to continue, or 'no' to cancel: no
[root@rockdev ~]#
```

**Comment by FroggyFlox** [comment]
The last commit https://github.com/rockstor/rockstor-core/pull/1962/commits/cf83caeb2f76c3fe5df18eed62c90e5d0a08321d fixes the last remaining fix that remained (as fas as I can think of): remove the "required" red asterisk from the device choice input fields to better reflect their optional nature.

**Comment by schakrava** [comment]
Very nicely done @FroggyFlox . Happy to merge it!

**Pull request merged**
