### PR TITLE
fix 'for' attributes on user_create_template labels

### PR DESCRIPTION
**Pull request by KaiRo-at**
I stumbled over the <label>s in user_create_template having a typo and missing for="" attributes, so I created a patch to fix this. ;-)

### CODE REVIEW

**Comment by schakrava** [comment]
Can one of the admins verify this patch?

**Comment by schakrava** [comment]
Can one of the admins verify this patch?

**Comment by phillxnet** [comment]
@KaiRo-at Cool and thanks.
@MFlyer Does this look OK to you?

**Comment by MFlyer** [comment]
Good to me @phillxnet , not tested, but it seems ok!
Mirko

**Comment by MFlyer** [comment]
To @schakrava : this can be merged too

Mirko

**Comment by schakrava** [comment]
Thank you @phillxnet and @MFlyer for your reviews. I apologize for the annoying/repeated message from the buildbot :)

Thanks for your contribution @KaiRo-at

**Pull request merged**
