### PR TITLE
correct the buildstatus.

### PR DESCRIPTION
**Pull request by schakrava**

### CODE REVIEW

**Comment by schakrava** [comment]
test

**Comment by schakrava** [comment]
test

**Comment by schakrava** [comment]
test

**Comment by schakrava** [comment]
test2

**Comment by MFlyer** [comment]
@schakrava : nice that :) , but is it normal I'm able to configure Jenkins builds?!?
M

**Comment by schakrava** [comment]
Yup, I have access to everyone in the team. I don't expect you to fiddle with stuff unless you really want to. Just trying to save some time by automating.

**Comment by MFlyer** [comment]
Thinking about build on every PR, but actually our build process takes some time

**Pull request merged**
