### PR TITLE
#1530 - Removing duplicated div id disk-details-ph, both on disk_util…

### PR DESCRIPTION
**Pull request by MFlyer**
Reference to #1530 

Required testing over Mac

### CODE REVIEW

**Comment by schakrava** [comment]
Thanks for working on this even though you are unable to reproduce it. I've tried on mac and sad to say the issue is still the same.

**Comment by MFlyer** [comment]
Hi @schakrava,
going to have a OS X El Capitan on a Virtualbox: having some code + asking you to test every time is like walking in the dark!
Here we come with our new game: will a 5GB ram WIN7 survive running OS X in Virtualbox? eheh

**Comment by phillxnet** [comment]
@MFlyer I normally have a rather old macbook pro hanging around who's sole use is to test stuff against Rockstor but I'm afraid it's been out on emergency loan for a couple of weeks. I'll let you know when I have it back and then I should be able to chip in on this one. Running pretty vanilla El Capitan (really slowly). Chase me up if I don't mention it for a bit.

Sorry for letting the side down on this one.

Maybe there is some trusty remote access software I can install to give you access, Note though that I'm double NATed here so that might be a problem. Hackintosh road is definitely a pretty bumpy one; in my experience.

**Comment by MFlyer** [comment]
Hi @phillxnet, thanks :D 
Today Hackintosh session over Virtualbox -> :feelsgood:  xD

**Pull request closed without merging**
