### PR TITLE
#1302 #1289 

### PR DESCRIPTION
**Pull request by MFlyer**
To @schakrava - As explained https://github.com/rockstor/rockstor-core/issues/1302#issuecomment-217856840 actually NetworkConnectionCollection doesn't point to devices so it's an empty list @phillxnet can you try this mod on a system with 2 interfaces over bond/team? :smiley: 
#1302 #1289

### CODE REVIEW

**Comment by phillxnet** [comment]
@MFlyer  Great. Currently I'm involved in another issue but after that and a bit more hw re-arrangements there after I can give it a go. But will be away tomorrow so it's not going to be that quick I'm afraid.

**Comment by schakrava** [comment]
@MFlyer  you are right that stats are being collected by the data-collector for devices(via /proc/net/dev) and not for connections. Nice find.

**Comment by schakrava** [comment]
With your patch, the numbers at the bottom of the widget are updating every few seconds as expected. This is good, it means data is coming through from the backend and being parsed properly for that part of the graph.

However, there's still a frontend bug which is preventing from the graph to be updated. So the graph is always blank. May be you'll find it interesting to dive in and see what's going on?

Here's a screenshot that might help a bit.
network_widget

**Comment by MFlyer** [comment]
Hi @schakrava, I'll check it asap! - Going on with last mods on logs manager

**Comment by MFlyer** [comment]
Hi @schakrava, got some news:
Tested and working on chrome, not on firefox

While logging:
Chrome at "time 0" get data.results with length = 2, while Firefox data.results has length to 0 raising errors (?!?)

I've also noticed that all line graphs (cpu too) don't render.

Generally speaking (pls ref. to #998) Firefox doesn't like svg ( poor performance and partial support [MDN page](https://developer.mozilla.org/en-US/docs/Web/SVG/SVG_1.1_Support_in_Firefox) ) so we should think about moving to canvas

Mirko/Flyer

**Pull request closed without merging**
